const players = [
  { role: "Batter", name: "Shubman Gill", country: "India", batting_style: "Right-handed", bowling_style: "Right-arm off break" },
  { role: "Batter", name: "Shreyas Iyer", country: "India", batting_style: "Right-handed", bowling_style: "Right-arm leg spin" },
  { role: "All-Rounder", name: "Ravindra Jadeja", country: "India", batting_style: "Left-handed", bowling_style: "Slow left arm orthodox" },
  { role: "Wicketkeeper", name: "Rishabh Pant", country: "India", batting_style: "Left-handed", bowling_style: "—" },
  { role: "All-Rounder", name: "Hardik Pandya", country: "India", batting_style: "Right-handed", bowling_style: "Right-arm medium-fast" },
  { role: "Batter", name: "KL Rahul", country: "India", batting_style: "Right-handed", bowling_style: "—" },
  { role: "Batter", name: "Yashasvi Jaiswal", country: "India", batting_style: "Left-handed", bowling_style: "Leg break" },
  { role: "All-Rounder", name: "Axar Patel", country: "India", batting_style: "Left-handed", bowling_style: "Slow left arm orthodox" },
  { role: "Batter", name: "Sanju Samson", country: "India", batting_style: "Right-handed", bowling_style: "—" },
  { role: "WicketKeeper", name: "Dhruv Jurel", country: "India", batting_style: "Right-handed", bowling_style: "—" },
  { role: "Bowler", name: "Jasprit Bumrah", country: "India", batting_style: "Right-handed", bowling_style: "Right-arm fast" },
  { role: "Bowler", name: "Mohammed Shami", country: "India", batting_style: "Right-handed", bowling_style: "Right-arm fast-medium" },
  { role: "Bowler", name: "Mohammed Siraj", country: "India", batting_style: "Right-handed", bowling_style: "Right-arm fast" },
  { role: "Bowler", name: "Kuldeep Yadav", country: "India", batting_style: "Left-handed", bowling_style: "Left-arm wrist spin" },
  { role: "Bowler", name: "Varun Chakaravarthy", country: "India", batting_style: "Right-handed", bowling_style: "Right-arm leg break" },
  { role: "Bowler", name: "Arshdeep Singh", country: "India", batting_style: "Left-handed", bowling_style: "Left-arm medium-fast" },
  { role: "Bowler", name: "Harshit Rana", country: "India", batting_style: "Right-handed", bowling_style: "Right-arm fast-medium" },
  { role: "Batter", name: "Tilak Varma", country: "India", batting_style: "Left-handed", bowling_style: "—" },
  { role: "Batter", name: "Rohit Sharma", country: "India", batting_style: "Right-handed", bowling_style: "Right-arm off break" },
  { role: "Batter", name: "Virat Kohli", country: "India", batting_style: "Right-handed", bowling_style: "Right-arm medium" },
  { role: "Batter", name: "Suryakumar Yadav", country: "India", batting_style: "Right-handed", bowling_style: "Right-arm medium" },
  { role: "Allrounder", name: "Shardul Thakur", country: "India", batting_style: "Right-handed", bowling_style: "Right-arm medium" },
  { role: "Bowler", name: "Prasidh Krishna", country: "India", batting_style: "Right-handed", bowling_style: "Right-arm fast-medium" },
  { role: "Bowler", name: "Ravi Bishnoi", country: "India", batting_style: "Right-handed", bowling_style: "Right-arm leg spin" },
  { role: "Allrounder", name: "Ramandeep Singh", country: "India", batting_style: "Right-handed", bowling_style: "Right-arm medium" },
  { role: "Allrounder", name: "Abhishek Sharma", country: "India", batting_style: "Left-handed", bowling_style: "Left-arm off spin" },
  { role: "Allrounder", name: "Nitish Kumar Reddy", country: "India", batting_style: "Right-handed", bowling_style: "Right-arm medium-fast" },
  { role: "Bowler", name: "Akash Deep", country: "India", batting_style: "Right-handed", bowling_style: "Right-arm fast-medium" },
  { role: "Bowler", name: "Anshul Kamboj", country: "India", batting_style: "Right-handed", bowling_style: "Right-arm medium" },
  { role: "Batter", name: "Abhimanyu Easwaran", country: "India", batting_style: "Right-handed", bowling_style: "—" },
  { role: "Batter", name: "Karun Nair", country: "India", batting_style: "Right-handed", bowling_style: "Right-arm off break" },
  { role: "Wicket-Keeper", name: "Narayan Jagadeesan", country: "India", batting_style: "Right-handed", bowling_style: "—" },
  { role: "AllRounder", name: "Shivam Dube", country: "India", batting_style: "Left-handed", bowling_style: "Right-arm medium-fast" },
  { role: "Batter", name: "Sai Sudharsan", country: "India", batting_style: "Left-handed", bowling_style: "—" },
  { role: "WicketKeeper", name: "Ishan Kishan", country: "India", batting_style: "Left-handed", bowling_style: "—" },
  { role: "AllRounder", name: "Devdutt Padikkal", country: "India", batting_style: "Left-handed", bowling_style: "—" },
  { role: "AllRounder", name: "Avesh Khan", country: "India", batting_style: "Right-handed", bowling_style: "Right-arm fast" },
  { role: "Batter", name: "David Warner", country: "Australia", batting_style: "Left-handed", bowling_style: "Right-arm legbreak" },
  { role: "Batter", name: "Steve Smith", country: "Australia", batting_style: "Right-handed", bowling_style: "Right-arm legbreak" },
  { role: "Batter", name: "Marnus Labuschagne", country: "Australia", batting_style: "Right-handed", bowling_style: "Right-arm legbreak" },
  { role: "Batter", name: "Usman Khawaja", country: "Australia", batting_style: "Left-handed", bowling_style: "Right-arm medium" },
  { role: "Batter", name: "Travis Head", country: "Australia", batting_style: "Left-handed", bowling_style: "Right-arm offbreak" },
  { role: "Batter", name: "Matt Renshaw", country: "Australia", batting_style: "Left-handed", bowling_style: "Right-arm offbreak" },
  { role: "Batter", name: "Marcus Harris", country: "Australia", batting_style: "Left-handed", bowling_style: "Right-arm medium" },
  { role: "Batter", name: "Peter Handscomb", country: "Australia", batting_style: "Right-handed", bowling_style: "Right-arm offbreak" },
  { role: "Batter", name: "Cameron Bancroft", country: "Australia", batting_style: "Right-handed", bowling_style: "Right-arm medium" },
  { role: "Batter", name: "Shaun Marsh", country: "Australia", batting_style: "Left-handed", bowling_style: "Right-arm offbreak" },
  { role: "Allrounder", name: "Cameron Green", country: "Australia", batting_style: "Right-handed", bowling_style: "Right-arm fast-medium" },
  { role: "Allrounder", name: "Glenn Maxwell", country: "Australia", batting_style: "Right-handed", bowling_style: "Right-arm offbreak" },
  { role: "Allrounder", name: "Mitchell Marsh", country: "Australia", batting_style: "Right-handed", bowling_style: "Right-arm medium-fast" },
  { role: "Allrounder", name: "Marcus Stoinis", country: "Australia", batting_style: "Right-handed", bowling_style: "Right-arm medium-fast" },
  { role: "Allrounder", name: "Ashton Agar", country: "Australia", batting_style: "Left-handed", bowling_style: "Slow left-arm orthodox" },
  { role: "Allrounder", name: "Hilton Cartwright", country: "Australia", batting_style: "Right-handed", bowling_style: "Right-arm medium" },
  { role: "Allrounder", name: "Aaron Hardie", country: "Australia", batting_style: "Right-handed", bowling_style: "Right-arm medium-fast" },
  { role: "Allrounder", name: "Moises Henriques", country: "Australia", batting_style: "Right-handed", bowling_style: "Right-arm medium-fast" },
  { role: "Allrounder", name: "Daniel Sams", country: "Australia", batting_style: "Left-handed", bowling_style: "Left-arm fast-medium" },
  { role: "Allrounder", name: "D’Arcy Short", country: "Australia", batting_style: "Left-handed", bowling_style: "Left-arm orthodox" },
  { role: "Bowler", name: "Pat Cummins", country: "Australia", batting_style: "Right-handed", bowling_style: "Right-arm fast" },
  { role: "Bowler", name: "Josh Hazlewood", country: "Australia", batting_style: "Left-handed", bowling_style: "Right-arm fast-medium" },
  { role: "Bowler", name: "Mitchell Starc", country: "Australia", batting_style: "Left-handed", bowling_style: "Left-arm fast" },
  { role: "Bowler", name: "Scott Boland", country: "Australia", batting_style: "Right-handed", bowling_style: "Right-arm fast-medium" },
  { role: "Bowler", name: "Jhye Richardson", country: "Australia", batting_style: "Right-handed", bowling_style: "Right-arm fast" },
  { role: "Bowler", name: "Sean Abbott", country: "Australia", batting_style: "Right-handed", bowling_style: "Right-arm fast-medium" },
  { role: "Bowler", name: "Kane Richardson", country: "Australia", batting_style: "Right-handed", bowling_style: "Right-arm fast-medium" },
  { role: "Bowler", name: "Nathan Ellis", country: "Australia", batting_style: "Right-handed", bowling_style: "Right-arm fast-medium" },
  { role: "Bowler", name: "Jason Behrendorff", country: "Australia", batting_style: "Left-handed", bowling_style: "Left-arm fast-medium" },
  { role: "Bowler", name: "Andrew Tye", country: "Australia", batting_style: "Right-handed", bowling_style: "Right-arm medium" },
  { role: "Bowler", name: "Adam Zampa", country: "Australia", batting_style: "Right-handed", bowling_style: "Right-arm legbreak" },
  { role: "Bowler", name: "Nathan Lyon", country: "Australia", batting_style: "Right-handed", bowling_style: "Right-arm offbreak" },
  { role: "Bowler", name: "Todd Murphy", country: "Australia", batting_style: "Right-handed", bowling_style: "Right-arm offbreak" },
  { role: "Bowler", name: "Mitchell Swepson", country: "Australia", batting_style: "Right-handed", bowling_style: "Right-arm legbreak" },
  { role: "Bowler", name: "Matthew Kuhnemann", country: "Australia", batting_style: "Left-handed", bowling_style: "Slow left-arm orthodox" },
  { role: "Bowler", name: "Tanveer Sangha", country: "Australia", batting_style: "Right-handed", bowling_style: "Right-arm legbreak" },
  { role: "Bowler", name: "Lance Morris", country: "Australia", batting_style: "Right-handed", bowling_style: "Right-arm fast" },
  { role: "Bowler", name: "Riley Meredith", country: "Australia", batting_style: "Right-handed", bowling_style: "Right-arm fast" },
  { role: "Bowler", name: "Chris Green", country: "Australia", batting_style: "Right-handed", bowling_style: "Right-arm offbreak" },
  { role: "Bowler", name: "Peter Siddle", country: "Australia", batting_style: "Right-handed", bowling_style: "Right-arm fast-medium" },
  { role: "Wicketkeeper", name: "Alex Carey", country: "Australia", batting_style: "Left-handed", bowling_style: "—" },
  { role: "Wicketkeeper", name: "Josh Inglis", country: "Australia", batting_style: "Right-handed", bowling_style: "—" },
  { role: "Wicketkeeper", name: "Matthew Wade", country: "Australia", batting_style: "Left-handed", bowling_style: "—" },
  { role: "Wicketkeeper", name: "Ben McDermott", country: "Australia", batting_style: "Right-handed", bowling_style: "Right-arm offbreak" },
  { role: "Wicketkeeper", name: "Sam Whiteman", country: "Australia", batting_style: "Left-handed", bowling_style: "—" },
  { role: "Wicketkeeper", name: "Josh Philippe", country: "Australia", batting_style: "Right-handed", bowling_style: "—" },
  { role: "Wicketkeeper", name: "Jimmy Peirson", country: "Australia", batting_style: "Right-handed", bowling_style: "—" },
  { role: "Wicketkeeper", name: "Cameron Bancroft", country: "Australia", batting_style: "Right-handed", bowling_style: "Right-arm medium" },
  { role: "Wicketkeeper", name: "Jake Doran", country: "Australia", batting_style: "Left-handed", bowling_style: "—" },
  { role: "Wicketkeeper", name: "Sam Harper", country: "Australia", batting_style: "Right-handed", bowling_style: "—" },
  { role: "Batter", name: "Jake Fraser-McGurk", country: "Australia", batting_style: "Right-handed", bowling_style: "Right-arm legbreak" },
  { role: "Batter", name: "Caleb Jewell", country: "Australia", batting_style: "Left-handed", bowling_style: "Right-arm offbreak" },
  { role: "Batter", name: "Nic Maddinson", country: "Australia", batting_style: "Left-handed", bowling_style: "Right-arm legbreak" },
  { role: "Batter", name: "Kurtis Patterson", country: "Australia", batting_style: "Left-handed", bowling_style: "Right-arm offbreak" },
  { role: "Batter", name: "Chris Lynn", country: "Australia", batting_style: "Right-handed", bowling_style: "Right-arm offbreak" },
  { role: "Batter", name: "Jake Weatherald", country: "Australia", batting_style: "Left-handed", bowling_style: "Right-arm offbreak" },
  { role: "Batter", name: "Tim David", country: "Australia", batting_style: "Right-handed", bowling_style: "Right-arm offbreak" },
  { role: "Batter", name: "Travis Dean", country: "Australia", batting_style: "Right-handed", bowling_style: "Right-arm offbreak" },
  { role: "Batter", name: "Oliver Davies", country: "Australia", batting_style: "Right-handed", bowling_style: "Right-arm offbreak" },
  { role: "Batter", name: "Jake Lehmann", country: "Australia", batting_style: "Left-handed", bowling_style: "Right-arm offbreak" },
  { role: "Allrounder", name: "Will Sutherland", country: "Australia", batting_style: "Right-handed", bowling_style: "Right-arm medium-fast" },
  { role: "Allrounder", name: "Jack Edwards", country: "Australia", batting_style: "Right-handed", bowling_style: "Right-arm medium" },
  { role: "Allrounder", name: "Matt Short", country: "Australia", batting_style: "Right-handed", bowling_style: "Right-arm offbreak" },
  { role: "Allrounder", name: "Jonathan Wells", country: "Australia", batting_style: "Right-handed", bowling_style: "Right-arm medium" },
  { role: "Allrounder", name: "Tom Rogers", country: "Australia", batting_style: "Right-handed", bowling_style: "Right-arm medium" },
  { role: "Allrounder", name: "Jack Wildermuth", country: "Australia", batting_style: "Right-handed", bowling_style: "Right-arm medium-fast" },
  { role: "Allrounder", name: "Beau Webster", country: "Australia", batting_style: "Right-handed", bowling_style: "Right-arm medium" },
  { role: "Allrounder", name: "Chris Tremain", country: "Australia", batting_style: "Right-handed", bowling_style: "Right-arm fast-medium" },
  { role: "Allrounder", name: "Nic Reardon", country: "Australia", batting_style: "Right-handed", bowling_style: "Right-arm offbreak" },
  { role: "Allrounder", name: "Nick Hobson", country: "Australia", batting_style: "Left-handed", bowling_style: "Right-arm offbreak" },
  { role: "Bowler", name: "Joel Paris", country: "Australia", batting_style: "Left-handed", bowling_style: "Left-arm fast-medium" },
  { role: "Bowler", name: "Ben Dwarshuis", country: "Australia", batting_style: "Left-handed", bowling_style: "Left-arm fast-medium" },
  { role: "Bowler", name: "Gurinder Sandhu", country: "Australia", batting_style: "Right-handed", bowling_style: "Right-arm medium-fast" },
  { role: "Bowler", name: "Mark Steketee", country: "Australia", batting_style: "Right-handed", bowling_style: "Right-arm fast-medium" },
  { role: "Bowler", name: "Chadd Sayers", country: "Australia", batting_style: "Right-handed", bowling_style: "Right-arm medium" },
  { role: "Bowler", name: "Peter Hatzoglou", country: "Australia", batting_style: "Right-handed", bowling_style: "Right-arm legbreak" },
  { role: "Bowler", name: "Michael Neser", country: "Australia", batting_style: "Right-handed", bowling_style: "Right-arm fast-medium" },
  { role: "Bowler", name: "Ben Manenti", country: "Australia", batting_style: "Right-handed", bowling_style: "Right-arm offbreak" },
  { role: "Bowler", name: "Tanveer Sangha", country: "Australia", batting_style: "Right-handed", bowling_style: "Right-arm legbreak" },
  { role: "Bowler", name: "Chris Tremain", country: "Australia", batting_style: "Right-handed", bowling_style: "Right-arm fast-medium" },
  { role: "Batter", name: "Shai Hope", country: "West Indies", batting_style: "Right-handed", bowling_style: "—" },
  { role: "Batter", name: "Shimron Hetmyer", country: "West Indies", batting_style: "Left-handed", bowling_style: "Right-arm offbreak" },
  { role: "Batter", name: "Nicholas Pooran", country: "West Indies", batting_style: "Left-handed", bowling_style: "—" },
  { role: "Batter", name: "Evin Lewis", country: "West Indies", batting_style: "Left-handed", bowling_style: "Right-arm medium" },
  { role: "Batter", name: "Brandon King", country: "West Indies", batting_style: "Right-handed", bowling_style: "Right-arm offbreak" },
  { role: "Batter", name: "Rovman Powell", country: "West Indies", batting_style: "Right-handed", bowling_style: "Right-arm medium" },
  { role: "Batter", name: "Kyle Mayers", country: "West Indies", batting_style: "Left-handed", bowling_style: "Right-arm medium" },
  { role: "Batter", name: "Johnson Charles", country: "West Indies", batting_style: "Right-handed", bowling_style: "—" },
  { role: "Batter", name: "Darren Bravo", country: "West Indies", batting_style: "Left-handed", bowling_style: "Right-arm medium" },
  { role: "Batter", name: "Sunil Ambris", country: "West Indies", batting_style: "Right-handed", bowling_style: "Right-arm offbreak" },
  { role: "Allrounder", name: "Jason Holder", country: "West Indies", batting_style: "Right-handed", bowling_style: "Right-arm fast-medium" },
  { role: "Allrounder", name: "Andre Russell", country: "West Indies", batting_style: "Right-handed", bowling_style: "Right-arm fast" },
  { role: "Allrounder", name: "Kieron Pollard", country: "West Indies", batting_style: "Right-handed", bowling_style: "Right-arm medium-fast" },
  { role: "Allrounder", name: "Fabian Allen", country: "West Indies", batting_style: "Left-handed", bowling_style: "Slow left-arm orthodox" },
  { role: "Allrounder", name: "Roston Chase", country: "West Indies", batting_style: "Right-handed", bowling_style: "Right-arm offbreak" },
  { role: "Allrounder", name: "Raymon Reifer", country: "West Indies", batting_style: "Left-handed", bowling_style: "Left-arm medium-fast" },
  { role: "Allrounder", name: "Sherfane Rutherford", country: "West Indies", batting_style: "Left-handed", bowling_style: "Right-arm medium" },
  { role: "Allrounder", name: "Romario Shepherd", country: "West Indies", batting_style: "Right-handed", bowling_style: "Right-arm fast-medium" },
  { role: "Allrounder", name: "Keemo Paul", country: "West Indies", batting_style: "Right-handed", bowling_style: "Right-arm medium-fast" },
  { role: "Allrounder", name: "Odean Smith", country: "West Indies", batting_style: "Right-handed", bowling_style: "Right-arm fast" },
  { role: "Bowler", name: "Alzarri Joseph", country: "West Indies", batting_style: "Right-handed", bowling_style: "Right-arm fast" },
  { role: "Bowler", name: "Kemar Roach", country: "West Indies", batting_style: "Right-handed", bowling_style: "Right-arm fast" },
  { role: "Bowler", name: "Shannon Gabriel", country: "West Indies", batting_style: "Right-handed", bowling_style: "Right-arm fast" },
  { role: "Bowler", name: "Obed McCoy", country: "West Indies", batting_style: "Right-handed", bowling_style: "Left-arm fast-medium" },
  { role: "Bowler", name: "Sheldon Cottrell", country: "West Indies", batting_style: "Right-handed", bowling_style: "Left-arm fast-medium" },
  { role: "Bowler", name: "Jayden Seales", country: "West Indies", batting_style: "Right-handed", bowling_style: "Right-arm fast" },
  { role: "Bowler", name: "Gudakesh Motie", country: "West Indies", batting_style: "Left-handed", bowling_style: "Slow left-arm orthodox" },
  { role: "Bowler", name: "Akeal Hosein", country: "West Indies", batting_style: "Left-handed", bowling_style: "Slow left-arm orthodox" },
  { role: "Bowler", name: "Hayden Walsh Jr.", country: "West Indies", batting_style: "Left-handed", bowling_style: "Right-arm legbreak" },
  { role: "Bowler", name: "Rahkeem Cornwall", country: "West Indies", batting_style: "Right-handed", bowling_style: "Right-arm offbreak" },
  { role: "Wicketkeeper", name: "Andre Fletcher", country: "West Indies", batting_style: "Right-handed", bowling_style: "—" },
  { role: "Wicketkeeper", name: "Denesh Ramdin", country: "West Indies", batting_style: "Right-handed", bowling_style: "—" },
  { role: "Wicketkeeper", name: "Chadwick Walton", country: "West Indies", batting_style: "Right-handed", bowling_style: "—" },
  { role: "Wicketkeeper", name: "Devon Thomas", country: "West Indies", batting_style: "Right-handed", bowling_style: "Right-arm medium" },
  { role: "Wicketkeeper", name: "Joshua Da Silva", country: "West Indies", batting_style: "Right-handed", bowling_style: "—" },
  { role: "Wicketkeeper", name: "Shane Dowrich", country: "West Indies", batting_style: "Right-handed", bowling_style: "—" },
  { role: "Wicketkeeper", name: "Tevin Imlach", country: "West Indies", batting_style: "Right-handed", bowling_style: "—" },
  { role: "Wicketkeeper", name: "Anthony Bramble", country: "West Indies", batting_style: "Right-handed", bowling_style: "—" },
  { role: "Wicketkeeper", name: "Jahmar Hamilton", country: "West Indies", batting_style: "Right-handed", bowling_style: "—" },
  { role: "Wicketkeeper", name: "Johnson Charles", country: "West Indies", batting_style: "Right-handed", bowling_style: "—" },
  { role: "Batter", name: "Keacy Carty", country: "West Indies", batting_style: "Right-handed", bowling_style: "Right-arm medium" },
  { role: "Batter", name: "Yannic Cariah", country: "West Indies", batting_style: "Left-handed", bowling_style: "Legbreak googly" },
  { role: "Bowler", name: "Kevin Sinclair", country: "West Indies", batting_style: "Right-handed", bowling_style: "Right-arm offbreak" },
  { role: "Bowler", name: "Jomel Warrican", country: "West Indies", batting_style: "Right-handed", bowling_style: "Slow left-arm orthodox" },
  { role: "Bowler", name: "Preston McSween", country: "West Indies", batting_style: "Left-handed", bowling_style: "Left-arm fast-medium" },
  { role: "Allrounder", name: "Justin Greaves", country: "West Indies", batting_style: "Right-handed", bowling_style: "Right-arm medium" },
  { role: "Allrounder", name: "Jonathan Carter", country: "West Indies", batting_style: "Left-handed", bowling_style: "Right-arm medium" },
  { role: "Allrounder", name: "Sunil Narine", country: "West Indies", batting_style: "Left-handed", bowling_style: "Right-arm offbreak" },
  { role: "Allrounder", name: "Ashley Nurse", country: "West Indies", batting_style: "Right-handed", bowling_style: "Right-arm offbreak" },
  { role: "Allrounder", name: "Carlos Brathwaite", country: "West Indies", batting_style: "Right-handed", bowling_style: "Right-arm fast-medium" },
  { role: "Batter", name: "Tamim Iqbal", country: "Bangladesh", batting_style: "Left-handed", bowling_style: "Right-arm offbreak" },
  { role: "Batter", name: "Litton Das", country: "Bangladesh", batting_style: "Right-handed", bowling_style: "—" },
  { role: "Batter", name: "Najmul Hossain Shanto", country: "Bangladesh", batting_style: "Left-handed", bowling_style: "Right-arm offbreak" },
  { role: "Batter", name: "Soumya Sarkar", country: "Bangladesh", batting_style: "Left-handed", bowling_style: "Right-arm medium-fast" },
  { role: "Batter", name: "Anamul Haque", country: "Bangladesh", batting_style: "Right-handed", bowling_style: "—" },
  { role: "Batter", name: "Shahriar Nafees", country: "Bangladesh", batting_style: "Left-handed", bowling_style: "Right-arm medium" },
  { role: "Batter", name: "Mahmudul Hasan Joy", country: "Bangladesh", batting_style: "Right-handed", bowling_style: "—" },
  { role: "Batter", name: "Mohammad Naim", country: "Bangladesh", batting_style: "Left-handed", bowling_style: "—" },
  { role: "Batter", name: "Imrul Kayes", country: "Bangladesh", batting_style: "Left-handed", bowling_style: "Right-arm offbreak" },
  { role: "Batter", name: "Towhid Hridoy", country: "Bangladesh", batting_style: "Right-handed", bowling_style: "Right-arm offbreak" },
  { role: "Allrounder", name: "Shakib Al Hasan", country: "Bangladesh", batting_style: "Left-handed", bowling_style: "Slow left-arm orthodox" },
  { role: "Allrounder", name: "Mahmudullah Riyad", country: "Bangladesh", batting_style: "Right-handed", bowling_style: "Right-arm offbreak" },
  { role: "Allrounder", name: "Mosaddek Hossain", country: "Bangladesh", batting_style: "Right-handed", bowling_style: "Right-arm offbreak" },
  { role: "Allrounder", name: "Afif Hossain", country: "Bangladesh", batting_style: "Left-handed", bowling_style: "Right-arm offbreak" },
  { role: "Allrounder", name: "Mehidy Hasan Miraz", country: "Bangladesh", batting_style: "Right-handed", bowling_style: "Right-arm offbreak" },
  { role: "Allrounder", name: "Shamim Hossain", country: "Bangladesh", batting_style: "Left-handed", bowling_style: "Right-arm offbreak" },
  { role: "Allrounder", name: "Nasir Hossain", country: "Bangladesh", batting_style: "Right-handed", bowling_style: "Right-arm offbreak" },
  { role: "Allrounder", name: "Mohammad Saifuddin", country: "Bangladesh", batting_style: "Left-handed", bowling_style: "Right-arm medium-fast" },
  { role: "Allrounder", name: "Aminul Islam Biplob", country: "Bangladesh", batting_style: "Right-handed", bowling_style: "Legbreak googly" },
  { role: "Allrounder", name: "Mahedi Hasan", country: "Bangladesh", batting_style: "Right-handed", bowling_style: "Right-arm offbreak" },
  { role: "Bowler", name: "Taskin Ahmed", country: "Bangladesh", batting_style: "Left-handed", bowling_style: "Right-arm fast" },
  { role: "Bowler", name: "Mustafizur Rahman", country: "Bangladesh", batting_style: "Left-handed", bowling_style: "Left-arm fast-medium" },
  { role: "Bowler", name: "Shoriful Islam", country: "Bangladesh", batting_style: "Left-handed", bowling_style: "Left-arm fast-medium" },
  { role: "Bowler", name: "Ebadot Hossain", country: "Bangladesh", batting_style: "Right-handed", bowling_style: "Right-arm fast-medium" },
  { role: "Bowler", name: "Abu Jayed Rahi", country: "Bangladesh", batting_style: "Right-handed", bowling_style: "Right-arm medium-fast" },
  { role: "Bowler", name: "Rubel Hossain", country: "Bangladesh", batting_style: "Right-handed", bowling_style: "Right-arm fast-medium" },
  { role: "Bowler", name: "Khaled Ahmed", country: "Bangladesh", batting_style: "Right-handed", bowling_style: "Right-arm fast-medium" },
  { role: "Bowler", name: "Tanvir Islam", country: "Bangladesh", batting_style: "Left-handed", bowling_style: "Slow left-arm orthodox" },
  { role: "Bowler", name: "Taijul Islam", country: "Bangladesh", batting_style: "Left-handed", bowling_style: "Slow left-arm orthodox" },
  { role: "Bowler", name: "Shuvagata Hom", country: "Bangladesh", batting_style: "Right-handed", bowling_style: "Right-arm offbreak" },
  { role: "Batter", name: "Babar Azam", country: "Pakistan", batting_style: "Right-handed", bowling_style: "Right-arm offbreak" },
  { role: "Batter", name: "Fakhar Zaman", country: "Pakistan", batting_style: "Left-handed", bowling_style: "Left-arm orthodox" },
  { role: "Batter", name: "Imam-ul-Haq", country: "Pakistan", batting_style: "Left-handed", bowling_style: "Right-arm legbreak" },
  { role: "Batter", name: "Shan Masood", country: "Pakistan", batting_style: "Left-handed", bowling_style: "Right-arm medium" },
  { role: "Batter", name: "Abdullah Shafique", country: "Pakistan", batting_style: "Right-handed", bowling_style: "Right-arm offbreak" },
  { role: "Batter", name: "Saim Ayub", country: "Pakistan", batting_style: "Left-handed", bowling_style: "Right-arm offbreak" },
  { role: "Batter", name: "Haider Ali", country: "Pakistan", batting_style: "Right-handed", bowling_style: "Right-arm medium" },
  { role: "Batter", name: "Asad Shafiq", country: "Pakistan", batting_style: "Right-handed", bowling_style: "Right-arm offbreak" },
  { role: "Batter", name: "Azhar Ali", country: "Pakistan", batting_style: "Right-handed", bowling_style: "Right-arm legbreak" },
  { role: "Batter", name: "Khushdil Shah", country: "Pakistan", batting_style: "Left-handed", bowling_style: "Slow left-arm orthodox" },
  { role: "Allrounder", name: "Shadab Khan", country: "Pakistan", batting_style: "Right-handed", bowling_style: "Right-arm legbreak" },
  { role: "Allrounder", name: "Mohammad Nawaz", country: "Pakistan", batting_style: "Left-handed", bowling_style: "Slow left-arm orthodox" },
  { role: "Allrounder", name: "Faheem Ashraf", country: "Pakistan", batting_style: "Left-handed", bowling_style: "Right-arm medium-fast" },
  { role: "Allrounder", name: "Imad Wasim", country: "Pakistan", batting_style: "Left-handed", bowling_style: "Slow left-arm orthodox" },
  { role: "Allrounder", name: "Agha Salman", country: "Pakistan", batting_style: "Right-handed", bowling_style: "Right-arm offbreak" },
  { role: "Allrounder", name: "Iftikhar Ahmed", country: "Pakistan", batting_style: "Right-handed", bowling_style: "Right-arm offbreak" },
  { role: "Allrounder", name: "Mohammad Hafeez", country: "Pakistan", batting_style: "Right-handed", bowling_style: "Right-arm offbreak" },
  { role: "Allrounder", name: "Amad Butt", country: "Pakistan", batting_style: "Right-handed", bowling_style: "Right-arm medium-fast" },
  { role: "Allrounder", name: "Anwar Ali", country: "Pakistan", batting_style: "Right-handed", bowling_style: "Right-arm medium-fast" },
  { role: "Allrounder", name: "Qasim Akram", country: "Pakistan", batting_style: "Right-handed", bowling_style: "Right-arm offbreak" },
  { role: "Bowler", name: "Shaheen Afridi", country: "Pakistan", batting_style: "Left-handed", bowling_style: "Left-arm fast" },
  { role: "Bowler", name: "Haris Rauf", country: "Pakistan", batting_style: "Right-handed", bowling_style: "Right-arm fast" },
  { role: "Bowler", name: "Naseem Shah", country: "Pakistan", batting_style: "Right-handed", bowling_style: "Right-arm fast" },
  { role: "Bowler", name: "Mohammad Amir", country: "Pakistan", batting_style: "Left-handed", bowling_style: "Left-arm fast" },
  { role: "Bowler", name: "Hasan Ali", country: "Pakistan", batting_style: "Right-handed", bowling_style: "Right-arm fast-medium" },
  { role: "Bowler", name: "Wahab Riaz", country: "Pakistan", batting_style: "Left-handed", bowling_style: "Left-arm fast" },
  { role: "Bowler", name: "Junaid Khan", country: "Pakistan", batting_style: "Left-handed", bowling_style: "Left-arm fast-medium" },
  { role: "Bowler", name: "Mohammad Wasim Jr.", country: "Pakistan", batting_style: "Right-handed", bowling_style: "Right-arm fast-medium" },
  { role: "Bowler", name: "Sohail Khan", country: "Pakistan", batting_style: "Right-handed", bowling_style: "Right-arm fast-medium" },
  { role: "Bowler", name: "Zaman Khan", country: "Pakistan", batting_style: "Right-handed", bowling_style: "Right-arm fast" },
  { role: "Bowler", name: "Yasir Shah", country: "Pakistan", batting_style: "Right-handed", bowling_style: "Right-arm legbreak" },
  { role: "Bowler", name: "Abrar Ahmed", country: "Pakistan", batting_style: "Right-handed", bowling_style: "Legbreak googly" },
  { role: "Bowler", name: "Sajid Khan", country: "Pakistan", batting_style: "Right-handed", bowling_style: "Right-arm offbreak" },
  { role: "Bowler", name: "Usama Mir", country: "Pakistan", batting_style: "Right-handed", bowling_style: "Right-arm legbreak" },
  { role: "Bowler", name: "Mohammad Irfan", country: "Pakistan", batting_style: "Left-handed", bowling_style: "Left-arm fast" },
  { role: "Bowler", name: "Rumman Raees", country: "Pakistan", batting_style: "Left-handed", bowling_style: "Left-arm medium-fast" },
  { role: "Bowler", name: "Tabraiz Shamsi", country: "Pakistan", batting_style: "Right-handed", bowling_style: "Right-arm offbreak" }, 
  { role: "Bowler", name: "Mir Hamza", country: "Pakistan", batting_style: "Left-handed", bowling_style: "Left-arm medium-fast" },
  { role: "Bowler", name: "Mohammad Musa", country: "Pakistan", batting_style: "Right-handed", bowling_style: "Right-arm fast" },
  { role: "Bowler", name: "Shahnawaz Dahani", country: "Pakistan", batting_style: "Right-handed", bowling_style: "Right-arm fast-medium" },
  { role: "Wicketkeeper", name: "Mohammad Rizwan", country: "Pakistan", batting_style: "Right-handed", bowling_style: "—" },
  { role: "Wicketkeeper", name: "Sarfaraz Ahmed", country: "Pakistan", batting_style: "Right-handed", bowling_style: "—" },
  { role: "Wicketkeeper", name: "Kamran Akmal", country: "Pakistan", batting_style: "Right-handed", bowling_style: "—" },
  { role: "Wicketkeeper", name: "Umar Akmal", country: "Pakistan", batting_style: "Right-handed", bowling_style: "Right-arm offbreak" },
  { role: "Wicketkeeper", name: "Rohail Nazir", country: "Pakistan", batting_style: "Right-handed", bowling_style: "—" },
  { role: "Wicketkeeper", name: "Mohammad Haris", country: "Pakistan", batting_style: "Right-handed", bowling_style: "Right-arm offbreak" },
  { role: "Wicketkeeper", name: "Zeeshan Ashraf", country: "Pakistan", batting_style: "Left-handed", bowling_style: "—" },
  { role: "Wicketkeeper", name: "Adnan Akmal", country: "Pakistan", batting_style: "Right-handed", bowling_style: "—" },
  { role: "Wicketkeeper", name: "Azam Khan", country: "Pakistan", batting_style: "Right-handed", bowling_style: "—" },
  { role: "Wicketkeeper", name: "Danish Aziz", country: "Pakistan", batting_style: "Left-handed", bowling_style: "Slow left-arm orthodox" },
  { role: "Allrounder", name: "Mohammad Nabi", country: "Afghanistan", batting_style: "Right-handed", bowling_style: "Right-arm offbreak" },
  { role: "Bowler", name: "Rashid Khan", country: "Afghanistan", batting_style: "Right-handed", bowling_style: "Right-arm legbreak" },
  { role: "Batsman", name: "Rahmanullah Gurbaz", country: "Afghanistan", batting_style: "Right-handed", bowling_style: "—" },
  { role: "Batsman", name: "Ibrahim Zadran", country: "Afghanistan", batting_style: "Right-handed", bowling_style: "Right-arm medium" },
  { role: "Batsman", name: "Hazratullah Zazai", country: "Afghanistan", batting_style: "Left-handed", bowling_style: "Right-arm offbreak" },
  { role: "Batsman", name: "Najibullah Zadran", country: "Afghanistan", batting_style: "Left-handed", bowling_style: "Right-arm offbreak" },
  { role: "Allrounder", name: "Gulbadin Naib", country: "Afghanistan", batting_style: "Right-handed", bowling_style: "Right-arm medium" },
  { role: "Bowler", name: "Mujeeb Ur Rahman", country: "Afghanistan", batting_style: "Right-handed", bowling_style: "Right-arm offbreak" },
  { role: "Bowler", name: "Fazalhaq Farooqi", country: "Afghanistan", batting_style: "Right-handed", bowling_style: "Left-arm fast-medium" },
  { role: "Batsman", name: "Usman Ghani", country: "Afghanistan", batting_style: "Right-handed", bowling_style: "Right-arm medium" },
  { role: "Bowler", name: "Naveen-ul-Haq", country: "Afghanistan", batting_style: "Right-handed", bowling_style: "Right-arm medium-fast" },
  { role: "Batsman", name: "Karim Janat", country: "Afghanistan", batting_style: "Right-handed", bowling_style: "Right-arm medium-fast" },
  { role: "Batsman", name: "Hashmatullah Shahidi", country: "Afghanistan", batting_style: "Left-handed", bowling_style: "Right-arm offbreak" },
  { role: "Batsman", name: "Afsar Zazai", country: "Afghanistan", batting_style: "Right-handed", bowling_style: "—" },
  { role: "Allrounder", name: "Sharafuddin Ashraf", country: "Afghanistan", batting_style: "Left-handed", bowling_style: "Left-arm orthodox" },
  { role: "Batsman", name: "Darwish Rasooli", country: "Afghanistan", batting_style: "Right-handed", bowling_style: "Right-arm offbreak" },
  { role: "Bowler", name: "Qais Ahmad", country: "Afghanistan", batting_style: "Right-handed", bowling_style: "Right-arm legbreak" },
  { role: "Allrounder", name: "Azmatullah Omarzai", country: "Afghanistan", batting_style: "Right-handed", bowling_style: "Right-arm fast-medium" },
  { role: "Bowler", name: "Hamid Hassan", country: "Afghanistan", batting_style: "Right-handed", bowling_style: "Right-arm fast" },
  { role: "Bowler", name: "Zahir Khan", country: "Afghanistan", batting_style: "Left-handed", bowling_style: "Left-arm wrist spin" },
  { role: "Bowler", name: "Amir Hamza", country: "Afghanistan", batting_style: "Right-handed", bowling_style: "Left-arm orthodox" },
  { role: "Bowler", name: "Dawlat Zadran", country: "Afghanistan", batting_style: "Right-handed", bowling_style: "Right-arm fast-medium" },
  { role: "Batsman", name: "Noor Ali Zadran", country: "Afghanistan", batting_style: "Right-handed", bowling_style: "Right-arm offbreak" },
  { role: "Batsman", name: "Shahidullah Kamal", country: "Afghanistan", batting_style: "Left-handed", bowling_style: "Right-arm offbreak" },
  { role: "Bowler", name: "Fareed Ahmad", country: "Afghanistan", batting_style: "Right-handed", bowling_style: "Left-arm fast-medium" },
  { role: "Bowler", name: "Shapoor Zadran", country: "Afghanistan", batting_style: "Right-handed", bowling_style: "Left-arm fast-medium" },
  { role: "Bowler", name: "Yamin Ahmadzai", country: "Afghanistan", batting_style: "Right-handed", bowling_style: "Right-arm medium-fast" },
  { role: "Batsman", name: "Ihsanullah Janat", country: "Afghanistan", batting_style: "Right-handed", bowling_style: "Right-arm medium" },
  { role: "Batsman", name: "Samiullah Shinwari", country: "Afghanistan", batting_style: "Right-handed", bowling_style: "Legbreak" },
  { role: "Batsman", name: "Aiden Markram", country: "South Africa", batting_style: "Right-handed", bowling_style: "Right-arm offbreak" },
  { role: "Batsman", name: "Temba Bavuma", country: "South Africa", batting_style: "Right-handed", bowling_style: "Right-arm medium" },
  { role: "Batsman", name: "Rassie van der Dussen", country: "South Africa", batting_style: "Right-handed", bowling_style: "Right-arm legbreak" },
  { role: "Batsman", name: "David Miller", country: "South Africa", batting_style: "Left-handed", bowling_style: "Right-arm offbreak" },
  { role: "Batsman", name: "Reeza Hendricks", country: "South Africa", batting_style: "Right-handed", bowling_style: "Right-arm offbreak" },  
  { role: "Allrounder", name: "Marco Jansen", country: "South Africa", batting_style: "Left-handed", bowling_style: "Left-arm fast-medium" },
  { role: "Allrounder", name: "Andile Phehlukwayo", country: "South Africa", batting_style: "Left-handed", bowling_style: "Right-arm medium-fast" },
  { role: "Allrounder", name: "Wiaan Mulder", country: "South Africa", batting_style: "Right-handed", bowling_style: "Right-arm medium-fast" },
  { role: "Allrounder", name: "Dwaine Pretorius", country: "South Africa", batting_style: "Right-handed", bowling_style: "Right-arm medium" },
  { role: "Allrounder", name: "Wayne Parnell", country: "South Africa", batting_style: "Left-handed", bowling_style: "Left-arm medium-fast" },
  { role: "Wicketkeeper", name: "Quinton de Kock", country: "South Africa", batting_style: "Left-handed", bowling_style: "—" },
  { role: "Wicketkeeper", name: "Heinrich Klaasen", country: "South Africa", batting_style: "Right-handed", bowling_style: "—" },
  { role: "Wicketkeeper", name: "Kyle Verreynne", country: "South Africa", batting_style: "Right-handed", bowling_style: "—" },
  { role: "Wicketkeeper", name: "Tristan Stubbs", country: "South Africa", batting_style: "Right-handed", bowling_style: "Right-arm offbreak" },  
{ role: "Wicketkeeper", name: "Ryan Rickelton", country: "South Africa", batting_style: "Left-handed", bowling_style: "—" },
{ role: "Bowler", name: "Kagiso Rabada", country: "South Africa", batting_style: "Left-handed", bowling_style: "Right-arm fast" },
{ role: "Bowler", name: "Anrich Nortje", country: "South Africa", batting_style: "Right-handed", bowling_style: "Right-arm fast" },
{ role: "Bowler", name: "Lungi Ngidi", country: "South Africa", batting_style: "Right-handed", bowling_style: "Right-arm fast-medium" },
{ role: "Bowler", name: "Gerald Coetzee", country: "South Africa", batting_style: "Right-handed", bowling_style: "Right-arm fast" },
{ role: "Bowler", name: "Sisanda Magala", country: "South Africa", batting_style: "Right-handed", bowling_style: "Right-arm medium-fast" },
{ role: "Bowler", name: "Keshav Maharaj", country: "South Africa", batting_style: "Right-handed", bowling_style: "Slow left-arm orthodox" },
{ role: "Bowler", name: "Tabraiz Shamsi", country: "South Africa", batting_style: "Right-handed", bowling_style: "Left-arm wrist spin" },
{ role: "Bowler", name: "Bjorn Fortuin", country: "South Africa", batting_style: "Left-handed", bowling_style: "Slow left-arm orthodox" },
{ role: "Bowler", name: "Dane Paterson", country: "South Africa", batting_style: "Right-handed", bowling_style: "Right-arm medium-fast" },
{ role: "Bowler", name: "Junior Dala", country: "South Africa", batting_style: "Right-handed", bowling_style: "Right-arm fast-medium" },
{ role: "Batsman", name: "Tony de Zorzi", country: "South Africa", batting_style: "Left-handed", bowling_style: "Right-arm offbreak" },
{ role: "Batsman", name: "Keegan Petersen", country: "South Africa", batting_style: "Right-handed", bowling_style: "Right-arm legbreak" },
{ role: "Batsman", name: "Dean Elgar", country: "South Africa", batting_style: "Left-handed", bowling_style: "Slow left-arm orthodox" },
{ role: "Batsman", name: "Ryan Rickelton", country: "South Africa", batting_style: "Left-handed", bowling_style: "—" },
{ role: "Batsman", name: "Zubayr Hamza", country: "South Africa", batting_style: "Right-handed", bowling_style: "Right-arm offbreak" },
{ role: "Bowler", name: "Beuran Hendricks", country: "South Africa", batting_style: "Right-handed", bowling_style: "Left-arm medium-fast" },
{ role: "Bowler", name: "Hardus Viljoen", country: "South Africa", batting_style: "Right-handed", bowling_style: "Right-arm fast-medium" },
{ role: "Bowler", name: "Duanne Olivier", country: "South Africa", batting_style: "Right-handed", bowling_style: "Right-arm fast-medium" },
{ role: "Bowler", name: "Glenton Stuurman", country: "South Africa", batting_style: "Right-handed", bowling_style: "Right-arm medium-fast" },
{ role: "Bowler", name: "Kyle Abbott", country: "South Africa", batting_style: "Right-handed", bowling_style: "Right-arm fast-medium" },
{ role: "Allrounder", name: "George Linde", country: "South Africa", batting_style: "Left-handed", bowling_style: "Slow left-arm orthodox" },
{ role: "Allrounder", name: "Daryn Dupavillon", country: "South Africa", batting_style: "Right-handed", bowling_style: "Right-arm fast" },
{ role: "Allrounder", name: "Chris Morris", country: "South Africa", batting_style: "Right-handed", bowling_style: "Right-arm fast-medium" },
{ role: "Allrounder", name: "Farhaan Behardien", country: "South Africa", batting_style: "Right-handed", bowling_style: "Right-arm medium" },
{ role: "Allrounder", name: "Senuran Muthusamy", country: "South Africa", batting_style: "Left-handed", bowling_style: "Slow left-arm orthodox" },
{ role: "Bowler", name: "Aaron Phangiso", country: "South Africa", batting_style: "Left-handed", bowling_style: "Slow left-arm orthodox" },
{ role: "Bowler", name: "Prenelan Subrayen", country: "South Africa", batting_style: "Right-handed", bowling_style: "Right-arm offbreak" },
{ role: "Bowler", name: "Ottniel Baartman", country: "South Africa", batting_style: "Right-handed", bowling_style: "Right-arm medium-fast" },
{ role: "Bowler", name: "Corbin Bosch", country: "South Africa", batting_style: "Right-handed", bowling_style: "Right-arm fast-medium" },
{ role: "Bowler", name: "Junior Dala", country: "South Africa", batting_style: "Right-handed", bowling_style: "Right-arm fast-medium" },
{ role: "Batsman", name: "Jason Smith", country: "South Africa", batting_style: "Right-handed", bowling_style: "Right-arm medium" },
{ role: "Batsman", name: "Jonathan Bird", country: "South Africa", batting_style: "Left-handed", bowling_style: "Right-arm offbreak" },
{ role: "Batsman", name: "Matthew Breetzke", country: "South Africa", batting_style: "Right-handed", bowling_style: "Right-arm medium" },
{ role: "Batsman", name: "Khaya Zondo", country: "South Africa", batting_style: "Right-handed", bowling_style: "Right-arm offbreak" },
{ role: "Batsman", name: "Pite van Biljon", country: "South Africa", batting_style: "Right-handed", bowling_style: "Right-arm medium" },
{ role: "Batsman", name: "Kane Williamson", country: "New Zealand", batting_style: "Right-handed", bowling_style: "Right-arm offbreak" },
{ role: "Batsman", name: "Devon Conway", country: "New Zealand", batting_style: "Left-handed", bowling_style: "Right-arm medium" },
{ role: "Batsman", name: "Will Young", country: "New Zealand", batting_style: "Right-handed", bowling_style: "Right-arm offbreak" },
{ role: "Batsman", name: "Mark Chapman", country: "New Zealand", batting_style: "Left-handed", bowling_style: "Slow left-arm orthodox" },
{ role: "Batsman", name: "Tom Latham", country: "New Zealand", batting_style: "Left-handed", bowling_style: "Right-arm medium" },
{ role: "Allrounder", name: "Daryl Mitchell", country: "New Zealand", batting_style: "Right-handed", bowling_style: "Right-arm medium" },
{ role: "Allrounder", name: "Michael Bracewell", country: "New Zealand", batting_style: "Left-handed", bowling_style: "Right-arm offbreak" },
{ role: "Allrounder", name: "Rachin Ravindra", country: "New Zealand", batting_style: "Left-handed", bowling_style: "Slow left-arm orthodox" },
{ role: "Allrounder", name: "Jimmy Neesham", country: "New Zealand", batting_style: "Left-handed", bowling_style: "Right-arm medium-fast" },
{ role: "Allrounder", name: "Mitchell Santner", country: "New Zealand", batting_style: "Left-handed", bowling_style: "Slow left-arm orthodox" },
{ role: "Bowler", name: "Trent Boult", country: "New Zealand", batting_style: "Right-handed", bowling_style: "Left-arm fast-medium" },
{ role: "Bowler", name: "Tim Southee", country: "New Zealand", batting_style: "Right-handed", bowling_style: "Right-arm medium-fast" },
{ role: "Bowler", name: "Lockie Ferguson", country: "New Zealand", batting_style: "Right-handed", bowling_style: "Right-arm fast" },
{ role: "Bowler", name: "Kyle Jamieson", country: "New Zealand", batting_style: "Right-handed", bowling_style: "Right-arm fast-medium" },
{ role: "Bowler", name: "Matt Henry", country: "New Zealand", batting_style: "Right-handed", bowling_style: "Right-arm fast-medium" },
{ role: "Bowler", name: "Adam Milne", country: "New Zealand", batting_style: "Right-handed", bowling_style: "Right-arm fast" },
{ role: "Bowler", name: "Ben Sears", country: "New Zealand", batting_style: "Right-handed", bowling_style: "Right-arm fast" },
{ role: "Bowler", name: "Ish Sodhi", country: "New Zealand", batting_style: "Right-handed", bowling_style: "Right-arm legbreak" },
{ role: "Bowler", name: "Ajaz Patel", country: "New Zealand", batting_style: "Left-handed", bowling_style: "Slow left-arm orthodox" },
{ role: "Bowler", name: "Blair Tickner", country: "New Zealand", batting_style: "Right-handed", bowling_style: "Right-arm medium-fast" },
{ role: "Batsman", name: "Finn Allen", country: "New Zealand", batting_style: "Right-handed", bowling_style: "Right-arm offbreak" },
{ role: "Batsman", name: "Martin Guptill", country: "New Zealand", batting_style: "Right-handed", bowling_style: "Right-arm offbreak" },
{ role: "Batsman", name: "Henry Nicholls", country: "New Zealand", batting_style: "Left-handed", bowling_style: "Right-arm offbreak" },
{ role: "Batsman", name: "Glenn Phillips", country: "New Zealand", batting_style: "Right-handed", bowling_style: "Right-arm offbreak" },
{ role: "Batsman", name: "Tom Blundell", country: "New Zealand", batting_style: "Right-handed", bowling_style: "Right-arm offbreak" },
{ role: "Allrounder", name: "Colin de Grandhomme", country: "New Zealand", batting_style: "Right-handed", bowling_style: "Right-arm medium-fast" },
{ role: "Allrounder", name: "Doug Bracewell", country: "New Zealand", batting_style: "Right-handed", bowling_style: "Right-arm fast-medium" },
{ role: "Allrounder", name: "Scott Kuggeleijn", country: "New Zealand", batting_style: "Right-handed", bowling_style: "Right-arm fast-medium" },
{ role: "Allrounder", name: "Dean Foxcroft", country: "New Zealand", batting_style: "Right-handed", bowling_style: "Right-arm offbreak" },
{ role: "Allrounder", name: "Cole McConchie", country: "New Zealand", batting_style: "Right-handed", bowling_style: "Right-arm offbreak" },
{ role: "Bowler", name: "Jacob Duffy", country: "New Zealand", batting_style: "Right-handed", bowling_style: "Right-arm medium-fast" },
{ role: "Bowler", name: "Hamish Bennett", country: "New Zealand", batting_style: "Right-handed", bowling_style: "Right-arm fast-medium" },
{ role: "Bowler", name: "Nathan Smith", country: "New Zealand", batting_style: "Right-handed", bowling_style: "Right-arm medium-fast" },
{ role: "Bowler", name: "Ben Lister", country: "New Zealand", batting_style: "Right-handed", bowling_style: "Left-arm medium-fast" },
{ role: "Bowler", name: "Kyle Abbott", country: "New Zealand", batting_style: "Right-handed", bowling_style: "Right-arm fast-medium" },
{ role: "Batsman", name: "George Worker", country: "New Zealand", batting_style: "Left-handed", bowling_style: "Slow left-arm orthodox" },
{ role: "Batsman", name: "Hamish Rutherford", country: "New Zealand", batting_style: "Left-handed", bowling_style: "Right-arm offbreak" },
{ role: "Batsman", name: "Jeet Raval", country: "New Zealand", batting_style: "Left-handed", bowling_style: "Right-arm legbreak" },
{ role: "Batsman", name: "Robert O’Donnell", country: "New Zealand", batting_style: "Right-handed", bowling_style: "Right-arm medium" },
{ role: "Batsman", name: "Leo Carter", country: "New Zealand", batting_style: "Left-handed", bowling_style: "Right-arm offbreak" },
{ role: "Allrounder", name: "Anaru Kitchen", country: "New Zealand", batting_style: "Left-handed", bowling_style: "Slow left-arm orthodox" },
{ role: "Allrounder", name: "Brett Hampton", country: "New Zealand", batting_style: "Right-handed", bowling_style: "Right-arm medium-fast" },
{ role: "Allrounder", name: "Anton Devcich", country: "New Zealand", batting_style: "Left-handed", bowling_style: "Slow left-arm orthodox" },
{ role: "Allrounder", name: "Todd Astle", country: "New Zealand", batting_style: "Right-handed", bowling_style: "Right-arm legbreak" },
{ role: "Allrounder", name: "James Franklin", country: "New Zealand", batting_style: "Left-handed", bowling_style: "Right-arm medium-fast" },
{ role: "Bowler", name: "Neil Wagner", country: "New Zealand", batting_style: "Left-handed", bowling_style: "Left-arm fast-medium" },
{ role: "Bowler", name: "Chris Martin", country: "New Zealand", batting_style: "Left-handed", bowling_style: "Right-arm fast-medium" },
{ role: "Bowler", name: "Brent Arnel", country: "New Zealand", batting_style: "Right-handed", bowling_style: "Right-arm medium-fast" },
{ role: "Bowler", name: "Graeme Aldridge", country: "New Zealand", batting_style: "Right-handed", bowling_style: "Right-arm fast-medium" },
{ role: "Bowler", name: "Michael Rae", country: "New Zealand", batting_style: "Right-handed", bowling_style: "Right-arm fast-medium" },
  { role: "Batsman", name: "Joe Root", country: "England", batting_style: "Right-handed", bowling_style: "Right-arm offbreak" },
  { role: "Batsman", name: "Zak Crawley", country: "England", batting_style: "Right-handed", bowling_style: "Right-arm offbreak" },
  { role: "Batsman", name: "Harry Brook", country: "England", batting_style: "Right-handed", bowling_style: "Right-arm medium" },
  { role: "Batsman", name: "Ollie Pope", country: "England", batting_style: "Right-handed", bowling_style: "Right-arm medium" },
  { role: "Batsman", name: "Dawid Malan", country: "England", batting_style: "Left-handed", bowling_style: "Right-arm legbreak" },
  { role: "Batsman", name: "Jason Roy", country: "England", batting_style: "Right-handed", bowling_style: "Right-arm medium" },
  { role: "Batsman", name: "Ben Duckett", country: "England", batting_style: "Left-handed", bowling_style: "Right-arm offbreak" },
  { role: "Batsman", name: "Alex Hales", country: "England", batting_style: "Right-handed", bowling_style: "Right-arm medium" },
  { role: "Batsman", name: "Rory Burns", country: "England", batting_style: "Left-handed", bowling_style: "Right-arm offbreak" },
  { role: "Allrounder", name: "Ben Stokes", country: "England", batting_style: "Left-handed", bowling_style: "Right-arm fast-medium" },
  { role: "Allrounder", name: "Moeen Ali", country: "England", batting_style: "Left-handed", bowling_style: "Right-arm offbreak" },
  { role: "Allrounder", name: "Sam Curran", country: "England", batting_style: "Left-handed", bowling_style: "Left-arm medium-fast" },
  { role: "Allrounder", name: "Chris Woakes", country: "England", batting_style: "Right-handed", bowling_style: "Right-arm fast-medium" },
  { role: "Allrounder", name: "Will Jacks", country: "England", batting_style: "Right-handed", bowling_style: "Right-arm offbreak" },
  { role: "Allrounder", name: "Liam Livingstone", country: "England", batting_style: "Right-handed", bowling_style: "Right-arm legbreak" },
  { role: "Allrounder", name: "David Willey", country: "England", batting_style: "Left-handed", bowling_style: "Left-arm fast-medium" },
  { role: "Allrounder", name: "Craig Overton", country: "England", batting_style: "Right-handed", bowling_style: "Right-arm fast-medium" },
  { role: "Allrounder", name: "Jamie Overton", country: "England", batting_style: "Right-handed", bowling_style: "Right-arm fast" },
  { role: "Allrounder", name: "Lewis Gregory", country: "England", batting_style: "Right-handed", bowling_style: "Right-arm medium-fast" },
  { role: "Bowler", name: "Jofra Archer", country: "England", batting_style: "Right-handed", bowling_style: "Right-arm fast" },
  { role: "Bowler", name: "Mark Wood", country: "England", batting_style: "Right-handed", bowling_style: "Right-arm fast" },
  { role: "Bowler", name: "Ollie Robinson", country: "England", batting_style: "Right-handed", bowling_style: "Right-arm fast-medium" },
  { role: "Bowler", name: "Chris Jordan", country: "England", batting_style: "Right-handed", bowling_style: "Right-arm fast-medium" },
  { role: "Bowler", name: "Adil Rashid", country: "England", batting_style: "Right-handed", bowling_style: "Right-arm legbreak" },
  { role: "Bowler", name: "Reece Topley", country: "England", batting_style: "Right-handed", bowling_style: "Left-arm fast-medium" },
  { role: "Bowler", name: "Brydon Carse", country: "England", batting_style: "Right-handed", bowling_style: "Right-arm fast" },
  { role: "Bowler", name: "Saqib Mahmood", country: "England", batting_style: "Right-handed", bowling_style: "Right-arm fast" },
  { role: "Bowler", name: "Tymal Mills", country: "England", batting_style: "Right-handed", bowling_style: "Left-arm fast" },
  { role: "Bowler", name: "Matthew Potts", country: "England", batting_style: "Right-handed", bowling_style: "Right-arm fast-medium" },
  { role: "Bowler", name: "George Garton", country: "England", batting_style: "Right-handed", bowling_style: "Left-arm fast-medium" },
  { role: "Bowler", name: "Jake Ball", country: "England", batting_style: "Right-handed", bowling_style: "Right-arm fast-medium" },
  { role: "Bowler", name: "Dom Bess", country: "England", batting_style: "Right-handed", bowling_style: "Right-arm offbreak" },
  { role: "Bowler", name: "Jack Leach", country: "England", batting_style: "Left-handed", bowling_style: "Left-arm orthodox" },
  { role: "Bowler", name: "Mason Crane", country: "England", batting_style: "Right-handed", bowling_style: "Right-arm legbreak" },
  { role: "Bowler", name: "Matt Parkinson", country: "England", batting_style: "Right-handed", bowling_style: "Right-arm legbreak" },
  { role: "Bowler", name: "Danny Briggs", country: "England", batting_style: "Left-handed", bowling_style: "Slow left-arm orthodox" },
  { role: "Bowler", name: "Liam Dawson", country: "England", batting_style: "Left-handed", bowling_style: "Slow left-arm orthodox" },
  { role: "Wicketkeeper", name: "Jonny Bairstow", country: "England", batting_style: "Right-handed", bowling_style: "—" },
  { role: "Wicketkeeper", name: "Jos Buttler", country: "England", batting_style: "Right-handed", bowling_style: "—" },
  { role: "Wicketkeeper", name: "Sam Billings", country: "England", batting_style: "Right-handed", bowling_style: "—" },
  { role: "Wicketkeeper", name: "Ben Foakes", country: "England", batting_style: "Right-handed", bowling_style: "—" },
  { role: "Wicketkeeper", name: "Phil Salt", country: "England", batting_style: "Right-handed", bowling_style: "—" },
  { role: "Wicketkeeper", name: "James Bracey", country: "England", batting_style: "Left-handed", bowling_style: "—" },
  { role: "Wicketkeeper", name: "Jordan Cox", country: "England", batting_style: "Right-handed", bowling_style: "—" },
  { role: "Wicketkeeper", name: "Tom Banton", country: "England", batting_style: "Right-handed", bowling_style: "—" },
  { role: "Wicketkeeper", name: "Adam Rossington", country: "England", batting_style: "Right-handed", bowling_style: "—" },
  { role: "Wicketkeeper", name: "John Simpson", country: "England", batting_style: "Left-handed", bowling_style: "—" },
  { role: "Batsman", name: "Keaton Jennings", country: "England", batting_style: "Left-handed", bowling_style: "Right-arm medium" },
  { role: "Batsman", name: "James Vince", country: "England", batting_style: "Right-handed", bowling_style: "Right-arm medium" },
  { role: "Batsman", name: "Laurie Evans", country: "England", batting_style: "Right-handed", bowling_style: "Right-arm offbreak" },
  { role: "Batsman", name: "Dan Lawrence", country: "England", batting_style: "Right-handed", bowling_style: "Right-arm offbreak" },
  { role: "Batsman", name: "Rob Keogh", country: "England", batting_style: "Right-handed", bowling_style: "Right-arm offbreak" },
  { role: "Batsman", name: "Stephen Eskinazi", country: "England", batting_style: "Right-handed", bowling_style: "—" },
  { role: "Batsman", name: "Sam Hain", country: "England", batting_style: "Right-handed", bowling_style: "—" },
  { role: "Batsman", name: "Tom Kohler-Cadmore", country: "England", batting_style: "Right-handed", bowling_style: "—" },
  { role: "Batsman", name: "Ben Compton", country: "England", batting_style: "Left-handed", bowling_style: "—" },
  { role: "Batsman", name: "Michael Jones", country: "England", batting_style: "Right-handed", bowling_style: "—" },
  { role: "Allrounder", name: "Paul Walter", country: "England", batting_style: "Left-handed", bowling_style: "Right-arm medium" },
  { role: "Allrounder", name: "Jordan Thompson", country: "England", batting_style: "Left-handed", bowling_style: "Right-arm medium-fast" },
  { role: "Allrounder", name: "Tom Abell", country: "England", batting_style: "Right-handed", bowling_style: "Right-arm medium" },
  { role: "Allrounder", name: "Luke Wright", country: "England", batting_style: "Right-handed", bowling_style: "Right-arm medium" },
  { role: "Allrounder", name: "Chris Jordan", country: "England", batting_style: "Right-handed", bowling_style: "Right-arm fast-medium" },
  { role: "Allrounder", name: "Ben Raine", country: "England", batting_style: "Left-handed", bowling_style: "Right-arm medium" },
  { role: "Allrounder", name: "Matt Critchley", country: "England", batting_style: "Right-handed", bowling_style: "Legbreak" },
  { role: "Allrounder", name: "Luke Wood", country: "England", batting_style: "Left-handed", bowling_style: "Left-arm fast-medium" },
  { role: "Allrounder", name: "George Balderson", country: "England", batting_style: "Left-handed", bowling_style: "Right-arm medium" },
  { role: "Allrounder", name: "Samit Patel", country: "England", batting_style: "Left-handed", bowling_style: "Slow left-arm orthodox" },
  { role: "Allrounder", name: "Dasun Shanaka", country: "Sri Lanka", batting_style: "Right-handed", bowling_style: "Right-arm medium" },
{ role: "Batsman", name: "Kusal Mendis", country: "Sri Lanka", batting_style: "Right-handed", bowling_style: "Right-arm medium" },
{ role: "Batsman", name: "Pathum Nissanka", country: "Sri Lanka", batting_style: "Right-handed", bowling_style: "Right-arm offbreak" },
{ role: "Batsman", name: "Charith Asalanka", country: "Sri Lanka", batting_style: "Left-handed", bowling_style: "Right-arm offbreak" },
{ role: "Batsman", name: "Dimuth Karunaratne", country: "Sri Lanka", batting_style: "Left-handed", bowling_style: "Right-arm medium" },
{ role: "Batsman", name: "Oshada Fernando", country: "Sri Lanka", batting_style: "Right-handed", bowling_style: "Right-arm offbreak" },
{ role: "Batsman", name: "Avishka Fernando", country: "Sri Lanka", batting_style: "Right-handed", bowling_style: "Right-arm medium" },
{ role: "Batsman", name: "Dinesh Chandimal", country: "Sri Lanka", batting_style: "Right-handed", bowling_style: "Right-arm offbreak" },
{ role: "Wicketkeeper", name: "Kusal Perera", country: "Sri Lanka", batting_style: "Left-handed", bowling_style: "Right-arm medium" },
{ role: "Wicketkeeper", name: "Sadeera Samarawickrama", country: "Sri Lanka", batting_style: "Right-handed", bowling_style: "Right-arm offbreak" },
{ role: "Allrounder", name: "Wanindu Hasaranga", country: "Sri Lanka", batting_style: "Right-handed", bowling_style: "Right-arm legbreak" },
{ role: "Allrounder", name: "Dhananjaya de Silva", country: "Sri Lanka", batting_style: "Right-handed", bowling_style: "Right-arm offbreak" },
{ role: "Allrounder", name: "Angelo Mathews", country: "Sri Lanka", batting_style: "Right-handed", bowling_style: "Right-arm medium-fast" },
{ role: "Allrounder", name: "Chamika Karunaratne", country: "Sri Lanka", batting_style: "Right-handed", bowling_style: "Right-arm medium-fast" },
{ role: "Allrounder", name: "Thisara Perera", country: "Sri Lanka", batting_style: "Left-handed", bowling_style: "Right-arm medium-fast" },
{ role: "Bowler", name: "Maheesh Theekshana", country: "Sri Lanka", batting_style: "Right-handed", bowling_style: "Right-arm offbreak" },
{ role: "Bowler", name: "Dilshan Madushanka", country: "Sri Lanka", batting_style: "Right-handed", bowling_style: "Left-arm fast-medium" },
{ role: "Bowler", name: "Matheesha Pathirana", country: "Sri Lanka", batting_style: "Right-handed", bowling_style: "Right-arm fast" },
{ role: "Bowler", name: "Kasun Rajitha", country: "Sri Lanka", batting_style: "Right-handed", bowling_style: "Right-arm fast-medium" },
{ role: "Bowler", name: "Lahiru Kumara", country: "Sri Lanka", batting_style: "Right-handed", bowling_style: "Right-arm fast" },
{ role: "Bowler", name: "Asitha Fernando", country: "Sri Lanka", batting_style: "Right-handed", bowling_style: "Right-arm fast-medium" },
{ role: "Bowler", name: "Praveen Jayawickrama", country: "Sri Lanka", batting_style: "Left-handed", bowling_style: "Left-arm orthodox" },
{ role: "Bowler", name: "Jeffrey Vandersay", country: "Sri Lanka", batting_style: "Right-handed", bowling_style: "Right-arm legbreak" },
{ role: "Bowler", name: "Akila Dananjaya", country: "Sri Lanka", batting_style: "Right-handed", bowling_style: "Right-arm offbreak" },
{ role: "Bowler", name: "Dushmantha Chameera", country: "Sri Lanka", batting_style: "Right-handed", bowling_style: "Right-arm fast" },
{ role: "Bowler", name: "Binura Fernando", country: "Sri Lanka", batting_style: "Left-handed", bowling_style: "Left-arm medium-fast" },
{ role: "Bowler", name: "Nuwan Pradeep", country: "Sri Lanka", batting_style: "Right-handed", bowling_style: "Right-arm fast-medium" },
{ role: "Bowler", name: "Ramesh Mendis", country: "Sri Lanka", batting_style: "Right-handed", bowling_style: "Right-arm offbreak" },
{ role: "Allrounder", name: "Lasantha Embuldeniya", country: "Sri Lanka", batting_style: "Left-handed", bowling_style: "Left-arm orthodox" },
{ role: "Bowler", name: "Vishwa Fernando", country: "Sri Lanka", batting_style: "Left-handed", bowling_style: "Left-arm fast-medium" },
{ role: "All-rounder", name: "Scott Edwards", country: "Netherlands", batting_style: "Right-handed", bowling_style: "Right-arm offbreak" },
{ role: "Bowler", name: "Paul van Meekeren", country: "Netherlands", batting_style: "Right-handed", bowling_style: "Right-arm fast-medium" },
{ role: "Bowler", name: "Logan van Beek", country: "Netherlands", batting_style: "Right-handed", bowling_style: "Right-arm fast-medium" },
{ role: "Batsman", name: "Max O'Dowd", country: "Netherlands", batting_style: "Right-handed", bowling_style: "Right-arm offbreak" },
{ role: "All-rounder", name: "Bas de Leede", country: "Netherlands", batting_style: "Right-handed", bowling_style: "Right-arm medium" },
{ role: "Bowler", name: "Fred Klaassen", country: "Netherlands", batting_style: "Right-handed", bowling_style: "Left-arm fast-medium" },
{ role: "Bowler", name: "Aryan Dutt", country: "Netherlands", batting_style: "Right-handed", bowling_style: "Right-arm offbreak" },
{ role: "All-rounder", name: "Teja Nidamanuru", country: "Netherlands", batting_style: "Right-handed", bowling_style: "Right-arm offbreak" },
{ role: "Batsman", name: "Vikramjit Singh", country: "Netherlands", batting_style: "Left-handed", bowling_style: "Right-arm medium" },
{ role: "Wicketkeeper", name: "Wesley Barresi", country: "Netherlands", batting_style: "Right-handed", bowling_style: "—" },
{ role: "All-rounder", name: "Richie Berrington", country: "Scotland", batting_style: "Right-handed", bowling_style: "Right-arm medium" },
{ role: "Bowler", name: "Safyaan Sharif", country: "Scotland", batting_style: "Right-handed", bowling_style: "Right-arm fast-medium" },
{ role: "Bowler", name: "Mark Watt", country: "Scotland", batting_style: "Right-handed", bowling_style: "Slow left-arm orthodox" },
{ role: "Wicketkeeper", name: "Matthew Cross", country: "Scotland", batting_style: "Right-handed", bowling_style: "—" },
{ role: "Batsman", name: "George Munsey", country: "Scotland", batting_style: "Left-handed", bowling_style: "Right-arm medium" },
{ role: "Bowler", name: "Chris Sole", country: "Scotland", batting_style: "Right-handed", bowling_style: "Right-arm fast" },
{ role: "Batsman", name: "Kyle Coetzer", country: "Scotland", batting_style: "Right-handed", bowling_style: "Right-arm medium" },
{ role: "All-rounder", name: "Michael Leask", country: "Scotland", batting_style: "Right-handed", bowling_style: "Right-arm offbreak" },
{ role: "All-rounder", name: "Chris Greaves", country: "Scotland", batting_style: "Right-handed", bowling_style: "Legbreak" },
{ role: "Bowler", name: "Adrian Neill", country: "Scotland", batting_style: "Right-handed", bowling_style: "Right-arm fast-medium" },
{ role: "Batsman", name: "Paul Stirling", country: "Ireland", batting_style: "Right-handed", bowling_style: "Right-arm offbreak" },
{ role: "Batsman", name: "Andrew Balbirnie", country: "Ireland", batting_style: "Right-handed", bowling_style: "—" },
{ role: "Bowler", name: "Joshua Little", country: "Ireland", batting_style: "Left-handed", bowling_style: "Left-arm fast-medium" },
{ role: "All-rounder", name: "Curtis Campher", country: "Ireland", batting_style: "Right-handed", bowling_style: "Right-arm medium" },
{ role: "Wicketkeeper", name: "Lorcan Tucker", country: "Ireland", batting_style: "Right-handed", bowling_style: "—" },
{ role: "All-rounder", name: "George Dockrell", country: "Ireland", batting_style: "Right-handed", bowling_style: "Slow left-arm orthodox" },
{ role: "Bowler", name: "Mark Adair", country: "Ireland", batting_style: "Right-handed", bowling_style: "Right-arm fast-medium" },
{ role: "Bowler", name: "Barry McCarthy", country: "Ireland", batting_style: "Right-handed", bowling_style: "Right-arm fast-medium" },
{ role: "Batsman", name: "Harry Tector", country: "Ireland", batting_style: "Right-handed", bowling_style: "Right-arm offbreak" },
{ role: "Bowler", name: "Andy McBrine", country: "Ireland", batting_style: "Left-handed", bowling_style: "Right-arm offbreak" },
{ role: "All-rounder", name: "Sikandar Raza", country: "Zimbabwe", batting_style: "Right-handed", bowling_style: "Right-arm offbreak" },
{ role: "Batsman", name: "Craig Ervine", country: "Zimbabwe", batting_style: "Left-handed", bowling_style: "Right-arm offbreak" },
{ role: "Batsman", name: "Sean Williams", country: "Zimbabwe", batting_style: "Left-handed", bowling_style: "Right-arm offbreak" },
{ role: "Wicketkeeper", name: "Regis Chakabva", country: "Zimbabwe", batting_style: "Right-handed", bowling_style: "–" },
{ role: "Batsman", name: "Wesley Madhevere", country: "Zimbabwe", batting_style: "Right-handed", bowling_style: "Right-arm offbreak" },
{ role: "Bowler", name: "Blessing Muzarabani", country: "Zimbabwe", batting_style: "Right-handed", bowling_style: "Right-arm fast" },
{ role: "Bowler", name: "Richard Ngarava", country: "Zimbabwe", batting_style: "Right-handed", bowling_style: "Left-arm fast-medium" },
{ role: "Batsman", name: "Milton Shumba", country: "Zimbabwe", batting_style: "Left-handed", bowling_style: "Right-arm offbreak" },
{ role: "All-rounder", name: "Ryan Burl", country: "Zimbabwe", batting_style: "Left-handed", bowling_style: "Right-arm legbreak" },
{ role: "Bowler", name: "Tendai Chatara", country: "Zimbabwe", batting_style: "Right-handed", bowling_style: "Right-arm fast-medium" },
{ role: "All-rounder", name: "Luke Jongwe", country: "Zimbabwe", batting_style: "Right-handed", bowling_style: "Right-arm medium-fast" },
{ role: "Wicketkeeper", name: "Clive Madande", country: "Zimbabwe", batting_style: "Right-handed", bowling_style: "–" },
{ role: "All-rounder", name: "Tony Munyonga", country: "Zimbabwe", batting_style: "Right-handed", bowling_style: "Right-arm offbreak" },
{ role: "Bowler", name: "Donald Tiripano", country: "Zimbabwe", batting_style: "Right-handed", bowling_style: "Right-arm medium-fast" },
{ role: "Bowler", name: "Victor Nyauchi", country: "Zimbabwe", batting_style: "Right-handed", bowling_style: "Right-arm fast-medium" },
{ role: "Bowler", name: "Tanaka Chivanga", country: "Zimbabwe", batting_style: "Right-handed", bowling_style: "Right-arm fast-medium" },
{ role: "Batsman", name: "Innocent Kaia", country: "Zimbabwe", batting_style: "Right-handed", bowling_style: "Right-arm legbreak" },
{ role: "Batsman", name: "Tadiwanashe Marumani", country: "Zimbabwe", batting_style: "Left-handed", bowling_style: "–" },
{ role: "All-rounder", name: "Brandon Mavuta", country: "Zimbabwe", batting_style: "Right-handed", bowling_style: "Right-arm legbreak" },
{ role: "All-rounder", name: "Tinotenda Mutombodzi", country: "Zimbabwe", batting_style: "Right-handed", bowling_style: "Right-arm legbreak" },
{ role: "Allrounder", name: "Paras Khadka", country: "Nepal", batting_style: "Right-handed", bowling_style: "Right-arm medium-fast" },
{ role: "Bowler", name: "Sandeep Lamichhane", country: "Nepal", batting_style: "Right-handed", bowling_style: "Right-arm legbreak" },
{ role: "Wicketkeeper", name: "Aasif Sheikh", country: "Nepal", batting_style: "Right-handed", bowling_style: "—" },
{ role: "Batsman", name: "Rohit Paudel", country: "Nepal", batting_style: "Right-handed", bowling_style: "Right-arm medium" },
{ role: "Allrounder", name: "Dipendra Singh Airee", country: "Nepal", batting_style: "Right-handed", bowling_style: "Right-arm offbreak" },
{ role: "Allrounder", name: "Monank Patel", country: "USA", batting_style: "Right-handed", bowling_style: "Right-arm offbreak" },
{ role: "Bowler", name: "Ali Khan", country: "USA", batting_style: "Right-handed", bowling_style: "Right-arm fast" },
{ role: "Batsman", name: "Steven Taylor", country: "USA", batting_style: "Left-handed", bowling_style: "Right-arm offbreak" },
{ role: "Allrounder", name: "Aaron Jones", country: "USA", batting_style: "Right-handed", bowling_style: "Right-arm legbreak" },
{ role: "Bowler", name: "Saurabh Netravalkar", country: "USA", batting_style: "Right-handed", bowling_style: "Left-arm medium" },
{ role: "Batsman", name: "Navneet Dhaliwal", country: "Canada", batting_style: "Right-handed", bowling_style: "Right-arm medium" },
{ role: "Wicketkeeper", name: "Hamza Tariq", country: "Canada", batting_style: "Right-handed", bowling_style: "—" },
{ role: "Allrounder", name: "Saad Bin Zafar", country: "Canada", batting_style: "Left-handed", bowling_style: "Left-arm orthodox" },
{ role: "Bowler", name: "Jeremy Gordon", country: "Canada", batting_style: "Right-handed", bowling_style: "Right-arm fast-medium" },
{ role: "Batsman", name: "Ravinderpal Singh", country: "Canada", batting_style: "Right-handed", bowling_style: "—" },
{ role: "Batsman", name: "Chirag Suri", country: "UAE", batting_style: "Left-handed", bowling_style: "—" },
{ role: "Bowler", name: "Zahoor Khan", country: "UAE", batting_style: "Right-handed", bowling_style: "Right-arm fast-medium" },
{ role: "Allrounder", name: "Rohan Mustafa", country: "UAE", batting_style: "Left-handed", bowling_style: "Right-arm offbreak" },
{ role: "Wicketkeeper", name: "Vriitya Aravind", country: "UAE", batting_style: "Right-handed", bowling_style: "—" },
{ role: "Batsman", name: "Muhammad Waseem", country: "UAE", batting_style: "Right-handed", bowling_style: "Right-arm medium" },
{ role: "Batsman", name: "Aqib Ilyas", country: "Oman", batting_style: "Right-handed", bowling_style: "Right-arm offbreak" },
{ role: "Wicketkeeper", name: "Khawar Ali", country: "Oman", batting_style: "Right-handed", bowling_style: "Right-arm legbreak" },
{ role: "Bowler", name: "Bilal Khan", country: "Oman", batting_style: "Right-handed", bowling_style: "Left-arm fast" },
{ role: "Allrounder", name: "Zeeshan Maqsood", country: "Oman", batting_style: "Left-handed", bowling_style: "Left-arm orthodox" },
{ role: "Batsman", name: "Jatinder Singh", country: "Oman", batting_style: "Right-handed", bowling_style: "Right-arm offbreak" },
{ role: "Wicketkeeper", name: "Scott McKechnie", country: "Hong Kong", batting_style: "Right-handed", bowling_style: "—" },
{ role: "Allrounder", name: "Nizakat Khan", country: "Hong Kong", batting_style: "Right-handed", bowling_style: "Right-arm legbreak" },
{ role: "Bowler", name: "Ehsan Khan", country: "Hong Kong", batting_style: "Right-handed", bowling_style: "Right-arm offbreak" },
{ role: "Batsman", name: "Babar Hayat", country: "Hong Kong", batting_style: "Right-handed", bowling_style: "—" },
{ role: "Bowler", name: "Aizaz Khan", country: "Hong Kong", batting_style: "Right-handed", bowling_style: "Right-arm medium-fast" },
{ role: "Allrounder", name: "Assad Vala", country: "PNG", batting_style: "Left-handed", bowling_style: "Right-arm offbreak" },
{ role: "Batsman", name: "Tony Ura", country: "PNG", batting_style: "Right-handed", bowling_style: "—" },
{ role: "Bowler", name: "Norman Vanua", country: "PNG", batting_style: "Right-handed", bowling_style: "Right-arm medium-fast" },
{ role: "Allrounder", name: "Charles Amini", country: "PNG", batting_style: "Left-handed", bowling_style: "Legbreak" },
{ role: "Wicketkeeper", name: "Kiplin Doriga", country: "PNG", batting_style: "Right-handed", bowling_style: "—" },
{ role: "Allrounder", name: "Gerhard Erasmus", country: "Namibia", batting_style: "Right-handed", bowling_style: "Right-arm offbreak" },
{ role: "Bowler", name: "Ruben Trumpelmann", country: "Namibia", batting_style: "Right-handed", bowling_style: "Left-arm fast-medium" },
{ role: "Batsman", name: "Michael van Lingen", country: "Namibia", batting_style: "Left-handed", bowling_style: "Right-arm medium" },
{ role: "Batsman", name: "Collins Obuya", country: "Kenya", batting_style: "Right-handed", bowling_style: "Legbreak" },
{ role: "Allrounder", name: "Rakep Patel", country: "Kenya", batting_style: "Right-handed", bowling_style: "Right-arm offbreak" },
{ role: "Bowler", name: "Nelson Odhiambo", country: "Kenya", batting_style: "Right-handed", bowling_style: "Right-arm medium-fast" },
{ role: "Allrounder", name: "Brian Masaba", country: "Uganda", batting_style: "Right-handed", bowling_style: "Right-arm legbreak" },
{ role: "Bowler", name: "Cosmas Kyewuta", country: "Uganda", batting_style: "Right-handed", bowling_style: "Right-arm fast-medium" },
{ role: "Batsman", name: "Roger Mukasa", country: "Uganda", batting_style: "Right-handed", bowling_style: "Right-arm offbreak" },
{ role: "Batsman", name: "Muhammad Younis", country: "Bahrain", batting_style: "Right-handed", bowling_style: "Right-arm offbreak" },
{ role: "Allrounder", name: "Junaid Nazir", country: "Bahrain", batting_style: "Left-handed", bowling_style: "Left-arm orthodox" },
{ role: "Bowler", name: "Imran Anwar", country: "Bahrain", batting_style: "Right-handed", bowling_style: "Right-arm medium" },
{ role: "Batsman", name: "Tamoor Sajjad", country: "Qatar", batting_style: "Right-handed", bowling_style: "Right-arm offbreak" },
{ role: "Bowler", name: "Iqbal Hussain", country: "Qatar", batting_style: "Right-handed", bowling_style: "Right-arm medium" },
{ role: "Allrounder", name: "Khawar Ali", country: "Qatar", batting_style: "Right-handed", bowling_style: "Right-arm legbreak" },
{ role: "Batsman", name: "Meet Bhavsar", country: "Kuwait", batting_style: "Left-handed", bowling_style: "Right-arm offbreak" },
{ role: "Allrounder", name: "Mohammed Aslam", country: "Kuwait", batting_style: "Right-handed", bowling_style: "Right-arm fast-medium" },
{ role: "Bowler", name: "Ravija Sandaruwan", country: "Kuwait", batting_style: "Right-handed", bowling_style: "Right-arm medium" },
{ role: "Batsman", name: "Usman Najeeb", country: "Saudi Arabia", batting_style: "Right-handed", bowling_style: "Right-arm offbreak" },
{ role: "Bowler", name: "Mohammad Afzal", country: "Saudi Arabia", batting_style: "Right-handed", bowling_style: "Right-arm medium" },
{ role: "Allrounder", name: "Zain Ul Abidin", country: "Saudi Arabia", batting_style: "Right-handed", bowling_style: "Right-arm legbreak" },
{ role: "Batsman", name: "Venkatraman Ganesan", country: "Germany", batting_style: "Right-handed", bowling_style: "Right-arm offbreak" },
{ role: "Allrounder", name: "Michael Richardson", country: "Germany", batting_style: "Right-handed", bowling_style: "Right-arm medium" },
{ role: "Bowler", name: "Faisal Bin Mubashir", country: "Germany", batting_style: "Right-handed", bowling_style: "Right-arm medium" },
{ role: "Batsman", name: "Gareth Berg", country: "Italy", batting_style: "Right-handed", bowling_style: "Right-arm medium-fast" },
{ role: "Allrounder", name: "Nico Maiolo", country: "Italy", batting_style: "Left-handed", bowling_style: "Left-arm orthodox" },
{ role: "Bowler", name: "Rakibul Hasan", country: "Italy", batting_style: "Right-handed", bowling_style: "Right-arm medium" },
{ role: "Batsman", name: "Harrison Carlyon", country: "Jersey", batting_style: "Right-handed", bowling_style: "Right-arm offbreak" },
{ role: "Allrounder", name: "Benjamin Ward", country: "Jersey", batting_style: "Right-handed", bowling_style: "Right-arm legbreak" },
{ role: "Bowler", name: "Charles Perchard", country: "Jersey", batting_style: "Right-handed", bowling_style: "Right-arm medium" },
{ role: "Batsman", name: "Christian Munoz-Mills", country: "Spain", batting_style: "Right-handed", bowling_style: "Right-arm offbreak" },
{ role: "Allrounder", name: "Hamza Dar", country: "Spain", batting_style: "Left-handed", bowling_style: "Left-arm orthodox" },
{ role: "Bowler", name: "Awais Ahmed", country: "Spain", batting_style: "Right-handed", bowling_style: "Right-arm medium" },
{ role: "Batsman", name: "Tim David", country: "Singapore", batting_style: "Right-handed", bowling_style: "Right-arm offbreak" },
{ role: "Allrounder", name: "Rohan Rangarajan", country: "Singapore", batting_style: "Right-handed", bowling_style: "Right-arm medium" },
{ role: "Bowler", name: "Janak Prakash", country: "Singapore", batting_style: "Right-handed", bowling_style: "Right-arm fast-medium" },
{ role: "Batsman", name: "Ahmad Faiz", country: "Malaysia", batting_style: "Right-handed", bowling_style: "Right-arm offbreak" },
{ role: "Allrounder", name: "Virandeep Singh", country: "Malaysia", batting_style: "Left-handed", bowling_style: "Right-arm legbreak" },
{ role: "Bowler", name: "Pavandeep Singh", country: "Malaysia", batting_style: "Right-handed", bowling_style: "Left-arm orthodox" },
{ role: "Batsman", name: "Frederik Klokker", country: "Denmark", batting_style: "Right-handed", bowling_style: "None" },
{ role: "Bowler", name: "Hamid Shah", country: "Denmark", batting_style: "Right-handed", bowling_style: "Right-arm offbreak" },
{ role: "All-rounder", name: "Raza Iqbal", country: "Norway", batting_style: "Left-handed", bowling_style: "Right-arm offbreak" },
{ role: "Bowler", name: "Khizer Ahmed", country: "Norway", batting_style: "Right-handed", bowling_style: "Right-arm medium" },
{ role: "Batsman", name: "Abhijit Venkatesh", country: "Sweden", batting_style: "Right-handed", bowling_style: "Right-arm medium" },
{ role: "Bowler", name: "Rahel Khan", country: "Sweden", batting_style: "Right-handed", bowling_style: "Right-arm offbreak" },
{ role: "Batsman", name: "Nathan Collins", country: "Finland", batting_style: "Right-handed", bowling_style: "None" },
{ role: "Bowler", name: "Mahesh Tambe", country: "Finland", batting_style: "Right-handed", bowling_style: "Right-arm medium" },
{ role: "All-rounder", name: "Shaheryar Butt", country: "Belgium", batting_style: "Right-handed", bowling_style: "Right-arm medium" },
{ role: "Bowler", name: "Saber Zakhil", country: "Belgium", batting_style: "Right-handed", bowling_style: "Right-arm offbreak" },
{ role: "Batsman", name: "Razmal Shigiwal", country: "Austria", batting_style: "Right-handed", bowling_style: "None" },
{ role: "Bowler", name: "Iqbal Hossain", country: "Austria", batting_style: "Right-handed", bowling_style: "Right-arm medium" },
{ role: "Batsman", name: "Faheem Nazir", country: "Switzerland", batting_style: "Right-handed", bowling_style: "Right-arm offbreak" },
{ role: "Bowler", name: "Arjun Vinod", country: "Switzerland", batting_style: "Right-handed", bowling_style: "Right-arm medium" },
{ role: "All-rounder", name: "Najam Shahzad", country: "Portugal", batting_style: "Right-handed", bowling_style: "Right-arm medium" },
{ role: "Bowler", name: "Francoise Stoman", country: "Portugal", batting_style: "Right-handed", bowling_style: "Right-arm offbreak" },
{ role: "Batsman", name: "Nicolas Maiquez", country: "France", batting_style: "Right-handed", bowling_style: "None" },
{ role: "Bowler", name: "Waseem Abbas", country: "France", batting_style: "Right-handed", bowling_style: "Right-arm medium" },
{ role: "All-rounder", name: "Anastasios Manousis", country: "Greece", batting_style: "Right-handed", bowling_style: "Right-arm medium" },
{ role: "Bowler", name: "Nikitas Rempakis", country: "Greece", batting_style: "Right-handed", bowling_style: "Right-arm offbreak" },
{ role: "Batsman", name: "Sudesh Wickramasekara", country: "Czech Republic", batting_style: "Right-handed", bowling_style: "Right-arm medium" },
{ role: "Bowler", name: "Satyajit Sengupta", country: "Czech Republic", batting_style: "Right-handed", bowling_style: "Right-arm offbreak" },
{ role: "Batsman", name: "Tony Whiteman", country: "Luxembourg", batting_style: "Right-handed", bowling_style: "None" },
{ role: "Bowler", name: "Anshuman Rathore", country: "Luxembourg", batting_style: "Right-handed", bowling_style: "Right-arm medium" },
{ role: "All-rounder", name: "Abhishek Awasthi", country: "Hungary", batting_style: "Right-handed", bowling_style: "Right-arm medium" },
{ role: "Bowler", name: "Haroon Malik", country: "Hungary", batting_style: "Right-handed", bowling_style: "Right-arm offbreak" },
{ role: "Batsman", name: "Vedran Zanko", country: "Croatia", batting_style: "Right-handed", bowling_style: "None" },
{ role: "Bowler", name: "Damir Sikic", country: "Croatia", batting_style: "Right-handed", bowling_style: "Right-arm medium" },
{ role: "Batsman", name: "Ramesh Satheesan", country: "Romania", batting_style: "Right-handed", bowling_style: "None" },
{ role: "Bowler", name: "Ijaz Hussain", country: "Romania", batting_style: "Right-handed", bowling_style: "Right-arm medium" },
{ role: "All-rounder", name: "Mark Pavlovic", country: "Serbia", batting_style: "Right-handed", bowling_style: "Right-arm medium" },
{ role: "Bowler", name: "Vukasin Zimonjic", country: "Serbia", batting_style: "Right-handed", bowling_style: "Right-arm offbreak" },
{ role: "Batsman", name: "Mehmet Sert", country: "Turkey", batting_style: "Right-handed", bowling_style: "None" },
{ role: "Bowler", name: "Burak Yilmaz", country: "Turkey", batting_style: "Right-handed", bowling_style: "Right-arm medium" },
{ role: "Batsman", name: "Louis Bruce", country: "Gibraltar", batting_style: "Right-handed", bowling_style: "None" },
{ role: "Bowler", name: "Charles Harrison", country: "Gibraltar", batting_style: "Right-handed", bowling_style: "Right-arm medium" },
{ role: "All-rounder", name: "Isaac Damarell", country: "Guernsey", batting_style: "Left-handed", bowling_style: "Right-arm medium" },
{ role: "Bowler", name: "Luke Bichard", country: "Guernsey", batting_style: "Right-handed", bowling_style: "Right-arm medium" },
{ role: "Batsman", name: "Adam McAuley", country: "Isle of Man", batting_style: "Right-handed", bowling_style: "None" },
{ role: "Bowler", name: "Jacob Butler", country: "Isle of Man", batting_style: "Right-handed", bowling_style: "Right-arm medium" },
{ role: "Allrounder", name: "Innocent Chinyemba", country: "Zambia", batting_style: "Right-handed", bowling_style: "Right-arm medium" },
{ role: "Batsman", name: "Sonam Tobgay", country: "Bhutan", batting_style: "Right-handed", bowling_style: "Right-arm medium" },
{ role: "Bowler", name: "Frederik Klokker", country: "Denmark", batting_style: "Left-handed", bowling_style: "Right-arm medium" },
{ role: "Batsman", name: "Diego Lord", country: "Argentina", batting_style: "Right-handed", bowling_style: "Right-arm offbreak" },
];

const Asia = ["India", "Pakistan", "Bangladesh", "Sri Lanka", "Nepal", "Afghanistan", "UAE", "OMAN" , "Saudi Arabia", "Hong Kong", "Bhutan", "Malaysia", "Singapore"];

const updatedPlayers = players.filter(player => Asia.includes(player.country))
.map(player => ({
  ...player,
  continent: "Asia"   // since all these countries are in Asia
}));

console.log(updatedPlayers);

